# Generated by Django 2.1.5 on 2019-01-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='finish_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termina em'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='start_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicia em'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(default='Sprint', max_length=200, verbose_name='Nome'),
        ),
    ]
