# Generated by Django 2.1.5 on 2019-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190113_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color_text',
            field=models.IntegerField(choices=[(1, 'Branco'), (2, 'Preto')], default=1, verbose_name='Cor do Texto'),
        ),
        migrations.AddField(
            model_name='status',
            name='color_text',
            field=models.IntegerField(choices=[(1, 'Branco'), (2, 'Preto')], default=1, verbose_name='Cor do Texto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tempo estimado em horas', max_digits=5, null=True, verbose_name='Tempo'),
        ),
    ]
