# Generated by Django 2.1.5 on 2019-01-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190113_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['start_on', 'finish_on', 'name'], 'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Ordem'),
        ),
    ]
