# Generated by Django 2.1.5 on 2019-01-14 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190113_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Tarefa'),
            preserve_default=False,
        ),
    ]
