# Generated by Django 2.1.5 on 2019-01-14 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190114_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
