# Generated by Django 2.1.5 on 2019-01-31 00:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190114_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Concluído?'),
        ),
        migrations.AddField(
            model_name='status',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Concluído?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Task', verbose_name='Tarefa pai'),
        ),
    ]
