# Generated by Django 2.1.5 on 2019-01-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_priority_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('color', models.CharField(default='#666666', max_length=7, verbose_name='Cor')),
                ('color_text', models.CharField(choices=[('#ffffff', 'Branco'), ('#000000', 'Preto')], default='#ffffff', max_length=7, verbose_name='Cor do Texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'task_type',
            },
        ),
    ]
