# Generated by Django 2.1.5 on 2019-01-31 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.TaskType', verbose_name='Tipo'),
        ),
    ]
