# Generated by Django 2.1.5 on 2019-02-07 19:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190205_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-start_on', '-finish_on', 'name'], 'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado?'),
        ),
    ]
