# Generated by Django 2.1.5 on 2019-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190207_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da arquivação'),
        ),
    ]
