# Generated by Django 2.1.5 on 2019-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_task_archived_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='archive',
        ),
    ]
