# Generated by Django 2.1.5 on 2019-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_status_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Concluido?'),
        ),
        migrations.AddField(
            model_name='task',
            name='done_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da conclusão'),
        ),
    ]
